name: flutter_signature_view
description: The signature plugin serve place to paint your signature and export it to many differences type to store.
version: 2.0.0
homepage: https://github.com/kzjn10/Flutter_SignatureWidget/tree/master/flutter_signature_view

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
